### ISSUE TITLE
[SauceLabs][Edge/IE/Safari] Large coverage data in POST are blocked in SauceLabs

### ISSUE THREAD

**Issue by t2ym** [t2ym/web-component-tester-istanbul#6]
[SauceLabs][Edge/IE/Safari] Large coverage data in POST are blocked in SauceLabs

## Root Cause
- With Edge/IE/Safari browsers, large HTTP POST requests (>80KB) are blocked by somewhere in between in SauceLabs.
- `500 Internal Server Error` from Server: monocle/0.24.1 (https://github.com/saucelabs/monocle)
  - The error may come from here https://github.com/saucelabs/monocle/blob/master/monocle/twisted_stack/network/http.py#L65
 as the server HTTP header is set at here `headers.setdefault('Server', 'monocle/%s' % VERSION)` https://github.com/saucelabs/monocle/blob/master/monocle/twisted_stack/network/http.py#L71
## Ad-hoc Workaround
- Use `@t2ym/web-component-tester@6.0.2` and `t2ym/web-component-tester#6.0.2` instead of `web-component-tester@^6.6.0`

## Notes
- Not reproducible with Chrome and Firefox on Windows 10

**Comment by t2ym** [comment]
The following error log from monocle is found in C:\log\chef.log.  This should be the root cause of 500 Internal Server Error.

```
2018-06-23 04:25:37,354 - monocle[log_exception:255] - ERROR - [1c4ff093f3b94ebf869de719cb5ce86e] 
Traceback (most recent call last):
  File "c:\chef\code\localhost_web_server.py", line 67, in proxy
  File "C:\Python27\lib\tempfile.py", line 402, in __getattr__
    a = getattr(file, name)
  -- trampolined off eventloop --
  File C:\Python27\lib\site-packages\twisted\internet\base.py, line 1169, in run
    self.mainLoop()
  File C:\Python27\lib\site-packages\twisted\internet\base.py, line 1181, in mainLoop
    self.doIteration(t)
  File C:\Python27\lib\site-packages\twisted\internet\selectreactor.py, line 144, in doSelect
    _logrun(selectable, _drdw, selectable, method, dict)
  File C:\Python27\lib\site-packages\twisted\python\log.py, line 84, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File C:\Python27\lib\site-packages\twisted\python\log.py, line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File C:\Python27\lib\site-packages\twisted\python\context.py, line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File C:\Python27\lib\site-packages\twisted\python\context.py, line 81, in callWithContext
    return func(*args,**kw)
  File C:\Python27\lib\site-packages\twisted\internet\selectreactor.py, line 150, in _doReadOrWrite
    why = getattr(selectable, method)()
  File C:\Python27\lib\site-packages\twisted\internet\tcp.py, line 203, in doRead
    return self._dataReceived(data)
  File C:\Python27\lib\site-packages\twisted\internet\tcp.py, line 209, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File C:\Python27\lib\site-packages\twisted\protocols\basic.py, line 572, in dataReceived
    return self.rawDataReceived(data)
  File C:\Python27\lib\site-packages\twisted\web\http.py, line 1622, in rawDataReceived
    self._transferDecoder.dataReceived(data)
  File C:\Python27\lib\site-packages\twisted\web\http.py, line 1349, in dataReceived
    finishCallback(data[contentLength:])
  File C:\Python27\lib\site-packages\twisted\web\http.py, line 1563, in _finishRequestBody
    self.allContentReceived()
  File C:\Python27\lib\site-packages\twisted\web\http.py, line 1618, in allContentReceived
    req.requestReceived(command, path, version)
  File C:\Python27\lib\site-packages\twisted\web\http.py, line 773, in requestReceived
    self.process()
  File C:\Python27\lib\site-packages\twisted\web\server.py, line 156, in process
    self.render(resrc)
  File C:\Python27\lib\site-packages\twisted\web\server.py, line 191, in render
    body = resrc.render(self)
  File C:\Python27\lib\site-packages\monocle\twisted_stack\network\http.py, line 62, in render
    _handler(request)
  -- eliding monocle internals --
  File C:\Python27\lib\site-packages\monocle\twisted_stack\network\http.py, line 33, in _handler
    value = yield launch(self.handler, request)
  -- eliding monocle internals --
AttributeError: 'file' object has no attribute 'getvalue'
2018-06-23 04:25:37,354 - monocle[log_exception:257] - ERROR - [1c4ff093f3b94ebf869de719cb5ce86e] 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\monocle\twisted_stack\network\http.py", line 34, in _handler
    code, headers, content = extract_response(value)
  File "C:\Python27\lib\site-packages\monocle\stack\network\http.py", line 271, in extract_response
    if len(value) == 2:
TypeError: object of type 'NoneType' has no len()
```

**Comment by t2ym** [comment]
## Root Cause Analysis

The latest monocle checks if the content has `'getvalue'` attribute ( https://github.com/saucelabs/monocle/blob/master/monocle/twisted_stack/network/http.py#L40 )

```python
                if hasattr(twisted_request.content, "getvalue"):
                    body = twisted_request.content.getvalue()
                else:
                    twisted_request.content.seek(0, os.SEEK_END)
                    if twisted_request.content.tell() <= self.max_body_str_len:
                        twisted_request.content.seek(0, os.SEEK_SET)
                        body = twisted_request.content.read()
                    twisted_request.content.seek(0, os.SEEK_SET)
```

It seems that the content is a `file` object generated as a temporary file and thus its content value should be obtained by `read()` from the position 0 of the file instead of `getvalue()` in localhost_web_server.py at line 67 with an effectively large size limit.

```
  File "c:\chef\code\localhost_web_server.py", line 67, in proxy
  File "C:\Python27\lib\tempfile.py", line 402, in __getattr__
...
AttributeError: 'file' object has no attribute 'getvalue'
```

## Notes from twisted
- https://github.com/twisted/twisted/blob/7ae439ff62d3599fc280791724b122f4b3c5c123/docs/web/howto/web-in-60/other-request-bodies.rst

`request.content` is a file-like object, so the body is read from it. The exact type may vary, so avoid relying on non-file methods you may find (such as `getvalue` when `request.content` happens to be a `BytesIO` instance).

- https://github.com/twisted/twisted/blob/trunk/src/twisted/web/http.py#L798

In this code, `request.content` is `StringIO` (= `BytesIO` here) if `length < 100000`, while `request.content` is `tempfile.TemporaryFile()` if `length >= 100000`

```python
    def gotLength(self, length):
        """
        Called when HTTP channel got length of content in this request.
        This method is not intended for users.
        @param length: The length of the request body, as indicated by the
            request headers.  L{None} if the request headers do not indicate a
            length.
        """
        if length is not None and length < 100000:
            self.content = StringIO()
        else:
            self.content = tempfile.TemporaryFile()
```

**Comment by t2ym** [comment]
Closing the issue as the fix released by Sauce Labs has been verified.

### As of January 9, 2019
- Sauce Labs Help Center reported that the fix had finally been deployed.
- The fix was verified with [i18n-behavior](https://github.com/t2ym/i18n-behavior/issues/67)

### As of July 18, 2018
- Still reproducible
- No updates from Sauce Labs Help Center

**Comment by t2ym** [comment]
Closing the issue as the fix released by Sauce Labs has been verified.
